import z from "zod"
import { ModelsDev } from "../src/provider/models"

export function modelsSnapshotSource(data: string): string {
  const snapshot = z.record(z.string(), ModelsDev.Provider).parse(JSON.parse(data))
  return `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${JSON.stringify(snapshot)} as const\n`
}
